packages:
  - packages/**
  - '!**/test/**'
link-workspace-packages: false
prefer-workspace-packages: false
shared-workspace-lockfile: true
save-workspace-protocol: true
storeDir: node_modules/.pnpm-store
virtualStoreDir: node_modules/.pnpm
registries:
  default: https://registry.npmmirror.com/
  official: https://registry.npmjs.org/
