packages:
  - packages/**
  - '!**/test/**'
linkWorkspacePackages: false
preferWorkspacePackages: false
sharedWorkspaceLockfile: true
saveWorkspaceProtocol: true
storeDir: node_modules/.pnpm-store
virtualStoreDir: node_modules/.pnpm
registries:
  default: https://registry.npmmirror.com/
  official: https://registry.npmjs.org/
